- hosts: host4

  vars:
    index_file: index.j2
    source_vh_config: virtualhost.j2
    vh_config_destination_folder: /etc/nginx/sites-available/
    site:
      - 2280
      - 2281
  tasks:
  - name: Install nginx server
    apt:
      name: nginx
      state: latest
      update_cache: yes

  - name: Copy virtual hosts config
    template: src={{ source_vh_config }} dest={{ vh_config_destination_folder }}virtualhost_{{ item }}.conf
    vars:
      port_site: "{{ item  }}"
    with_items: "{{ site }}"

  - name: Make link to config
    shell: "ln -s /etc/nginx/sites-available/virtualhost_{{ item }}.conf /etc/nginx/sites-enabled/virtualhost_{{ item }}.conf"
    with_items: "{{ site }}"
    register: results
    failed_when: results.rc != 0 and "File exist" not in results.stderr

  - name: Make dir for site files
    file:
      path: "/var/www/site{{ item }}/html"
      state: directory
    with_items: "{{ site }}"

  - name: Generate index.html
    template: src={{ index_file }} dest=/var/www/site{{ item }}/html/index.html
    vars:
      port_site: "{{ item  }}"
    with_items: "{{ site }}"

  - name: Check nginx config
    shell: "nginx -t"
    register: results
    failed_when: results.rc != 0 or "test failed" in results.stdout

  - name: Restart nginx
    shell: "nginx -s reload"

  - name: Check sites
    uri:
      url: http://{{ ansible_host }}:{{ item }}
    loop: "{{ site }}"
    delegate_to: host3
