name: PODs check
on:
  - push
jobs:
  checks:
    runs-on: vm3
    name: Checks
    steps:
    
    - name: install packages
      id: install
      run: |
        sudo apt-get -y update
        sudo apt-get -y install sshuttle
        sudo snap install kubectl --classic

        
    - name: Connect via SSH
      id: ssh_connect
      run: |
        ping -c 4 178.124.206.53
        ssh -o ProxyCommand="ssh -W %h:%p -q jump_sa@178.124.206.53" -L 6443:127.0.0.1:6443 root@192.168.203.2 -f -N
        
    - name: Clone repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Making dir for config
      continue-on-error: true
      run: |
        sudo rm -R ~/.kube
        sudo rm pods.err
        sudo mkdir ~/.kube
        echo 'WARNING!!!
        Check pods:' >> pods.err
        
        
    - name: Copy config
      if: always()
      continue-on-error: true
      run: |
        sudo cp 10.Kubernetes.WS/config ~/.kube
        
    - name: Checking_debug
      id: checking_debug
      run: kubectl get pods -A | sed -n '/NAME/,$p'
        
        
    - name: Test checking
      id: test_checking
      run: kubectl get pods -A | sed -n '/NAME/,$p' | sed '/NAME/d' | sed '/Running/d' | wc -l >> test.txt

    - name: Checking
      id: checking
      run: echo "count_failed_pods=$(kubectl get pods -A | sed -n '/NAME/,$p' | sed '/NAME/d' | sed '/Running/d' | wc -l)" >> "$GITHUB_OUTPUT"

    - name: Check var
      run: echo ${{ steps.checking.outputs.count_failed_pods }}
 
    - name: Get failed pods
      id: get_failed_pods
      if: ${{ steps.checking.outputs.count_failed_pods > 0 }}
      run: |
        kubectl get pods -A | sed '/Running/d' >> pods.err
        cat pods.err

    - name: Slack OK notification
      uses: rtCamp/action-slack-notify@v2
      if: ${{ steps.checking.outputs.count_failed_pods > 0 }}
      env:
        SLACK_CHANNEL: ivan_belov_slack_notification
        SLACK_COLOR: 'red'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: '$(cat pods.err)'
        SLACK_TITLE: ALARM
        SLACK_USERNAME: rtCamp
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}