name: PODs check
on:
  - push
jobs:
  checks:
    runs-on: vm3
    name: Checks
    steps:
    
    - name: install packages
      id: install
      run: |
        sudo apt-get -y update
        sudo apt-get -y install sshuttle
        sudo snap install kubectl --classic

        
    - name: Connect via SSH
      id: ssh_connect
      run: |
        ping -c 5 178.124.206.53
        sudo sshuttle -r 'jump_sa':'$F|BoF4+JK'@178.124.206.53 192.168.0.0/16 &

    - name: Cheking
      id: checking
      run: kubectl get pods
        
