name: PODs check
on:
  - push
jobs:
  checks:
    runs-on: vm3
    name: Checks
    steps:
    
    - name: install packages
      id: install
      run: |
        sudo apt-get update
        sudo apt-get install sshuttle
        sudo snap install kubectl --classic

        
    - name: Connect via SSH
      id: ssh_connect
      run: ping -c 4 178.124.206.53

#      run: sudo sshuttle -r 'jump_sa':'$F|BoF4+JK'@178.124.206.53 192.168.0.0/16 &

 #   - name: Chacking
 #     id: checking
  #    run: kubectl get pods
        
