name: changes
on: [push]
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          githubRepo: chicaragua/ITA
      - name: test
        run: |
          cat $HOME/files.json
      - name: list files
        run: ls -la
