name: changes
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: install jq
        run: sudo apt update && sudo apt install -y jq

      # Example 1
      - name: Get changed files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
          
      - name: list files
        run: ls -la

      - name: List all changed files
        run: echo ${{ steps.files.outputs.modified  }} >> 1.json

      - name: Show JSON from file
        run: jq .[0] 1.json

#      - name: Show JSON from env
#        run: jq .[0] ${{ steps.changed-files.outputs.all_changed_files  }}
