name: changes
on: [push]
jobs:
  build-matrix:
    runs-on: ubuntu-latest
    name: Building matrix   
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get changed files
        id  : changed-files
        uses: tj-actions/changed-files@v34
        with:
          json: "true"
      
      - name: Make JSON
        run : echo ${{ steps.changed-files.outputs.all_changed_files  }} >> files.json
      
      - name: List files in folder
        run : ls -ll
      
    outputs:
      matrix: ${{ fromJson(files.json) }} 


#  build:
#    runs-on: ubuntu-latest  # windows-latest | macos-latest
#    name: 
#    steps:
#     - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      # Example 1
#      - name: Get changed files
#        id: changed-files
#        uses: tj-actions/changed-files@v34
#        with:
#          json: "true"
#      
#      - name: list files
#        run: ls -la
#      - name: List all changed files
#        run: echo ${{ steps.changed-files.outputs.all_changed_files  }} >> 1.json
#
#      - name: Show JSON from file
#        run: cat 1.json


