name: changes
on: [push]
env:
  GLOBAL_COUNTER: 0
jobs:
  build-matrix:
    runs-on: ubuntu-latest
    name: Building matrix  
    outputs:
      matrix: ${{ steps.set-matrix.outputs.array }}
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get changed files
        id  : changed-files
        uses: tj-actions/changed-files@v34
        with:
          json: "true"
      
      - name: Make matrix
        id  : make-matrix
        run : cat 04.GIT_actions/test.json
      
      - name: List files in folder
        run : ls -ll
        
      - name: List matrix
        run: echo ${{ steps.make-matrix }} 
      
      
      - name: set matrix
        id  : set-matrix
   #    run : echo "matrix-files=${{ steps.changed-files.outputs.all_changed_files }}"
        run : echo "array={\"container\":${{ steps.changed-files.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"
      - name: Add global
        run : ${{ env.GLOBAL_COUNTER }} ++
        



  build:
    needs  : build-matrix
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name   : Test changed-files

    strategy:
        matrix: ${{ fromJSON(needs.build-matrix.outputs.matrix) }}
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set env
        id  : set-env
        run: |
          COUNTER=$(cat ${{ matrix.container }} | tr -dc \\t | wc -c)          
          FILENAME=$(echo  ${{ matrix.container }} | sed 's|.*/||') 
          echo "In file $FILENAME is $COUNTER tabs"
      - name: Show global
        run : ${{ env.GLOBAL_COUNTER }}

  global:
    needs: build
    runs-on: ubuntu-latest
    name: Global count
    steps:
      - name: Show global 
        run : echo ${{ env.GLOBAL_COUNTER }}
