name: changes
on: [push]
jobs:
  build-matrix:
    runs-on: ubuntu-latest
    name: Building matrix   
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Get changed files
        id  : changed-files
        uses: tj-actions/changed-files@v34
        with:
          json: "true"
      
      - name: Make matrix
        id  : make-matrix
        run : cat 04.GIT_actions/test.json
      
      - name: List files in folder
        run : ls -ll
      
      
 #     - name: set matrix
 #      id  : set-matrix
 #       run : echo "matrix-files=${{ steps.changed-files.outputs.all_changed_files }}"
      
    outputs:
      matrix-files: ${{ steps.make-matrix.outputs.matrix-files }} 


  build:
    needs: build-matrix
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
 #   strategy:
#      matrix: ${{ fromJSON(needs.build-matrix.outputs.matrix-files) }}
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      # Example 1
      
      
      - name: list files
        run: ls -la
      - name: List matrix
        run: echo "${{ needs.build-matrix.outputs.matrix-files }}"

      - name: Show JSON from file
        run: cat 1.json


